version: '2'
services:
  jupyter:
    build: ./
    restart: always
    ports:
    - "8888:8888"
    working_dir: /usr/src/app/
    volumes:
    - ./:/usr/src/app/
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --config=/usr/src/app/jupyter_notebook_config.py
    env_file: .env